# Ordens de serviço

## Registra novo usuário [/api/register]

### Register [POST]
+ Request (application/json)

    ```
    {
      "name" : "testerson",
      "email": "teste@teste.com",
      "password": "12345678",
      "password_confirmation": "12345678"
    }
    ```

+ Response 200 (application/json)

    ```
    {
      "user": {
          "name": "testerson",
          "email": "testde@teste.com",
          "updated_at": "2023-12-01T01:59:10.000000Z",
          "created_at": "2023-12-01T01:59:10.000000Z",
          "id": 5
      },
      "message": "Created successfully!"
    }
    ```

## Acessa usuário para criar token para autenticação [/api/login]

### Login [POST]
+ Request (application/json)

    ```
    {
      "email": "teste@teste.com",
      "password": "12345678",
    }
    ```

+ Response 200 (application/json)

    ```
    {
      "token": "Use este token",
    }
    ```

## Obtém usuário [/api/me]

### Current User [GET]
+ Request (application/json)

    ```
    {
      "Authorization Bearer" : "token"
    }
    ```

+ Response 200 (application/json)

    ```
    {
      "id":2,
      "name":"testerson",
      "email":"teste@test.com",
      "created_at":"2023-11-26T04:42:48.000000Z",
      "updated_at":"2023-11-26T04:42:48.000000Z"
    }
    ```
    
    
## Cria nova ordem de serviço [/api/service-order]

### Create [POST]

+ Request (application/json)

    ```
    {
      "vehiclePlate": "ABC1234",
      "entryDateTime": "2023-11-26T12:00:00",
      "exitDateTime": "2023-11-26T15:30:00",
      "priceType": "Hourly",
      "price": "100.00",
      "userId": 2
    }
    ```

+ Response 201 (application/json)

    ```
    {
      "vehiclePlate": "ABC1234",
      "entryDateTime": "2023-11-26T12:00:00",
      "exitDateTime": "2023-11-26T15:30:00",
      "priceType": "Hourly",
      "price": "100.00",
      "userId": 2,
      "updated_at": "2023-11-26T04:50:53.000000Z",
      "created_at": "2023-11-26T04:50:53.000000Z",
      "id": 2
    }
    ```

## Lista coleções de ordens [/api/service-orders]

### Index [GET]

+ Response 200 (application/json)

    ```
      {
        "current_page": 1,
        "data": [
          {
            "id": 6,
            "vehiclePlate": "ABBC222",
            "entryDateTime": "2023-11-26 12:00:00",
            "exitDateTime": "2023-11-26 15:30:00",
            "priceType": "Hourly",
            "price": "100.00",
            "userId": 2,
            "created_at": "2023-11-30T04:44:38.000000Z",
            "updated_at": "2023-11-30T04:44:38.000000Z",
            "user": {
              "id": 2,
              "name": "admin",
              "email": "admin@test.com",
              "created_at": "2023-11-26T04:42:48.000000Z",
              "updated_at": "2023-11-26T04:42:48.000000Z"
            }
          },
          {
            "id": 7,
            "vehiclePlate": "CBA4321",
            "entryDateTime": "2023-11-26 12:00:00",
            "exitDateTime": "2023-11-26 15:30:00",
            "priceType": "Hourly",
            "price": "100.00",
            "userId": 2,
            "created_at": "2023-11-30T04:44:55.000000Z",
            "updated_at": "2023-11-30T04:44:55.000000Z",
            "user": {
              "id": 2,
              "name": "admin",
              "email": "admin@test.com",
              "created_at": "2023-11-26T04:42:48.000000Z",
              "updated_at": "2023-11-26T04:42:48.000000Z"
            }
          },
          {
            "id": 8,
            "vehiclePlate": "CBB4321",
            "entryDateTime": "2023-11-26 12:00:00",
            "exitDateTime": "2023-11-26 15:30:00",
            "priceType": "Hourly",
            "price": "100.00",
            "userId": 2,
            "created_at": "2023-12-01T02:02:08.000000Z",
            "updated_at": "2023-12-01T02:02:08.000000Z",
            "user": {
              "id": 2,
              "name": "admin",
              "email": "admin@test.com",
              "created_at": "2023-11-26T04:42:48.000000Z",
              "updated_at": "2023-11-26T04:42:48.000000Z"
            }
          }
        ],
        "first_page_url": "http://https://abdalazard-api.com/api/service-orders?page=1",
        "from": 1,
        "last_page": 1,
        "last_page_url": "http://https://abdalazard-api.com/api/service-orders?page=1",
        "links": [
          {
            "url": null,
            "label": "&laquo; Previous",
            "active": false
          },
          {
            "url": "http://https://abdalazard-api.com/api/service-orders?page=1",
            "label": "1",
            "active": true
          },
          {
            "url": null,
            "label": "Next &raquo;",
            "active": false
          }
        ],
        "next_page_url": null,
        "path": "http://https://abdalazard-api.com/api/service-orders",
        "per_page": 5,
        "prev_page_url": null,
        "to": 3,
        "total": 3
      }
    ```

## Atualiza ordem de serviço [/api/service-order/Id]

### Update [PUT]

+ Request (application/json)

    ```
    {
      "vehiclePlate": "XYZ7890",
      "price": 20.00
    }
    ```

+ Response 200 (application/json)

    ```
    {
      "message": "Service order updated successfully",
      "0": {
          "id": 6,
          "vehiclePlate": "XYZ7890",
          "entryDateTime": "2023-11-26 12:00:00",
          "exitDateTime": "2023-11-26 15:30:00",
          "priceType": "Hourly",
          "price": 20,
          "userId": 2,
          "created_at": "2023-11-30T04:44:38.000000Z",
          "updated_at": "2023-12-01T02:11:34.000000Z"
        }
    }
    ```

## Exclui uma ordem de serviço [/api/service-order/id]

### Delete [DELETE]

+ Response 200 (application/json)
    ```
    {
      "message": "Service order deleted successfully"
    }
    